//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppBookFair
{
    using System;
    using System.Collections.Generic;
    
    public partial class BF_Books
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public short PublishYear { get; set; }
        public string ISBN { get; set; }
        public int Price { get; set; }
        public System.Guid IdUser { get; set; }
        public string Cover { get; set; }
        public Nullable<byte> State { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual BF_Users User { get; set; }
    }
}
